channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - argh=0.26.2
  - astroid=2.4.1
  - atomicwrites=1.4.0
  - attrs=19.3.0
  - autopep8=1.5.2
  - babel=2.8.0
  - backcall=0.1.0
  - bcrypt=3.1.7
  - bleach=3.1.5
  - brotlipy=0.7.0
  - ca-certificates=2020.4.5.1
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - cloudpickle=1.4.1
  - colorama=0.4.3
  - cryptography=2.9.2
  - cycler=0.10.0
  - decorator=4.4.2
  - defusedxml=0.6.0
  - diff-match-patch=20181111
  - docutils=0.16
  - entrypoints=0.3
  - flake8=3.7.9
  - freetype=2.10.2
  - future=0.18.2
  - icu=64.2
  - idna=2.9
  - imagesize=1.2.0
  - importlib-metadata=1.6.0
  - importlib_metadata=1.6.0
  - intel-openmp=2020.0
  - intervaltree=3.0.2
  - ipykernel=5.3.0
  - ipython=7.14.0
  - ipython_genutils=0.2.0
  - isort=4.3.21
  - jedi=0.15.2
  - jinja2=2.11.2
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter_client=6.1.3
  - jupyter_core=4.6.3
  - keyring=21.2.1
  - kiwisolver=1.2.0
  - lazy-object-proxy=1.4.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - liblapack=3.8.0
  - libpng=1.6.37
  - libsodium=1.0.17
  - libspatialindex=1.9.3
  - markupsafe=1.1.1
  - matplotlib=3.2.1
  - matplotlib-base=3.2.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2020.0
  - nbconvert=5.6.1
  - nbformat=5.0.6
  - numpy=1.18.4
  - numpydoc=0.9.2
  - openssl=1.1.1g
  - packaging=20.4
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - paramiko=2.7.1
  - parso=0.5.2
  - pathtools=0.1.2
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - pluggy=0.13.1
  - prompt-toolkit=3.0.5
  - psutil=5.7.0
  - pycodestyle=2.5.0
  - pycparser=2.20
  - pydocstyle=5.0.2
  - pyflakes=2.1.1
  - pygments=2.6.1
  - pylint=2.5.2
  - pynacl=1.3.0
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.12.3
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.7.7
  - python-dateutil=2.8.1
  - python-jsonrpc-server=0.3.4
  - python-language-server=0.31.10
  - python_abi=3.7
  - pytz=2020.1
  - pywin32=227
  - pywin32-ctypes=0.2.0
  - pyyaml=5.3.1
  - pyzmq=19.0.1
  - qdarkstyle=2.8.1
  - qt=5.12.5
  - qtawesome=0.7.2
  - qtconsole=4.7.4
  - qtpy=1.9.0
  - requests=2.23.0
  - rope=0.17.0
  - rtree=0.9.4
  - setuptools=46.4.0
  - six=1.15.0
  - snowballstemmer=2.0.0
  - sortedcontainers=2.1.0
  - sphinx=3.0.3
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=1.0.3
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.4
  - spyder=4.1.3
  - spyder-kernels=1.9.1
  - sqlite=3.31.1
  - testpath=0.4.4
  - toml=0.10.1
  - tornado=6.0.4
  - traitlets=4.3.3
  - typed-ast=1.4.1
  - ujson=1.35
  - urllib3=1.25.9
  - vc=14.1
  - vs2015_runtime=14.16.27012
  - watchdog=0.10.2
  - wcwidth=0.1.9
  - webencodings=0.5.1
  - wheel=0.34.2
  - win_inet_pton=1.1.0
  - wincertstore=0.2
  - wrapt=1.11.2
  - yaml=0.2.4
  - yapf=0.29.0
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - emipy==0.0.4
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1


