name: Tests using Pytest
on: [push, pull_request]

jobs:
  test_pytest:
    runs-on: ubuntu-latest
    steps:
      - run: pip install . pytest pytest-cov geopandas
      - run: python -m pytest --cov=emipy tests/